name: Component cd pipeline

# Controls when the WF will run
on: 
  workflow_call:
  workflow_dispatch:
  push:
   branches:
   - main
jobs:
  example_job:
    runs-on: windows-latest
    steps:
      - name: List workflow runs
        run: |
         GH_WORKFLOW_STATE=$( curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO_SECRET }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Deeksha2o/Helloworld/commits/9dfa07d2a84a9226720006a220d6d8aa96154563/check-runs | jq -r '[.check_runs[] | select(.name == "example_job") ] | .[-1].conclusion')
         echo "state is ${GH_WORKFLOW_STATE}"
